name: Featurebranch
on:
  push:
    branches:
      - android_*

jobs:
  # ==========================================================================
  # Build Android app
  buildARM:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ Android/Dockerfile ]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build docker images
        run: docker build -t local -f Docker/${{ matrix.distro }}_noUpload --build-arg BUILD_THREADS=2 .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
