name: Android-Featurebranch
on:
  push:
    branches:
      - android_*

jobs:
  # ==========================================================================
  # Build Android app
  buildAndroid:
    runs-on: self-hosted
    strategy:
      matrix:
        distro: [ Android/Dockerfile ]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Provide keystore
        run: cp /etc/ssl/certs/AliasWalletAndroidKeyStore.jks ${{ github.workspace }}/

      - name: Build app using Docker
        run: >
          docker build
          -t local-${{ github.run_number }}
          -f Docker/${{ matrix.distro }}_noUpload
          --rm
          --build-arg BUILD_THREADS=8
          .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}

      - name: Cleanup Docker images
        run: docker rmi local-${{ github.run_number }}
